BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
	BBBBBBBBBB
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Title') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter title of your question here') X XXXXXXXXX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter title of question') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Text') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter text of your question') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Tags') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'tag1,tag2') XX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXXXXX
				XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'prove that your not a robot') X XXXXXXXXX
				 gettext(u'before you enter') 
			XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Ask!') XXXXXXXXX
	XXXXXX
XXXXXXX
BBBBBBBB
