BBBB BBBBBBBBBBB
BBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
	XXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
		XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
		XXXXXXX gettext(u'AskIt! - %(title)s') SSSSSS S SSSSSSSSSXXXXXXXX
	XXXXXXX
	XXXXXX
		XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
										  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXX gettext(u'Toggle navigation{%% ') XXXXXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXX
					XX XXXXXXXXX
						XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
					XXXX
				XXXXXXXXXX XXXXXXXXXXXXXXX XXX
				
				XXXX XXXXXXX XXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXX
				XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
						XXXX
							XX XXXXXXXXXXX XXXXXXBBB BBBBBXX
								XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXXXX gettext(u'ASK!') XXXXXXXXX
								XXXXXXXXX
							XXXX
						XXXXX
						XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						BB BBBBBBBBBBBBBBBBBBBBB
							XXX XXXXXXXXXXXXX XXXXXXXXXX
								XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXX XXXXXXXXXXXXXXXXXX
									    						XXXXXXX
									
									XXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXX
								XXX XXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBB BBBBBBBBBBBBBXX
											XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Profile') 
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX
											XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Settings') 
										XXXX
									XXXXX
									XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
											XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Logout') 
										XXXX
									XXXXX
								XXXXX
							XXXXX
						BBBB
							XXX XXXXXXXXXXXXXXX
								XX XXXXXXBBB BBBBBBBXX gettext(u'Login') XXXX
							XXXXX
						BBBBB
					XXXXX
					XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBXX
						XXXX XXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXX gettext(u'Search for...') XX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXXXXX
							XXXXXXX
						XXXXXXXXXX XXXXXXXXXXXX XXX
					XXXXXXX
				XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
			XXXXXXXXXX XXXXXXXXXXX XXX
		XXXXXX
		BB BBBBB
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		BBBBB
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
					BBBBB BBBBBBB
		    			BBBBBBBB
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
						XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
							 gettext(u'© Boyarskikh Nikita, 2017<br> Phone: 8 (916) 385-7622<br> E-Mail:') S SSSSSSSSSS SSSSSSS SSSSSSSS
							SSSSSS S SSSSS SSSSSSSSSSSS
							SSSSSSS XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXX gettext(u'Popular tags:') XXXXX
					BBB B BB BBBB
						XX XXXXXXBBB BBBBB BBBBXX
							XXXXX XXXXXXXXXXXXXXXXXFFFFXXX
								     XXXXXXXXXXXXX
								     XXXXXX XXXX
								     		   FFFFX
								     		   FFFFX
								     		   FFFF
										XXXX
								
							XXXXXXX
						XXXX
					BBBBB
						XXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'There are no tags yet...') XXXXXXX
					BBBBBB
			XXXXXX
			XXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXX gettext(u'Best answerers:') XXXXX
				XXXX
					BBB B BB BBBBBBBBB
						XX XXXXXXBBB BBBBBB BBBBBBBBBBXX
							XXX XXXXXXXXXXXXXXX
								XXXX XXXXXX XXXXXXXXXXXXXXXXXX
													XXXXXXX 
							XXXXX
						XXXX
					BBBBB
						XXX XXXXXXXXXXXXXXX
							 gettext(u'There are no users yet...') 
						XXXXX
					BBBBBB
				XXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXX XXXXXX XXX
		XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Back to Top') XXXX
		XXXX
		XXXX XXXXXXX XXXXXX XXX
		XXXX XXX XXXXXXXXXXXXX XXXXXXXXX X XX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXX
		XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XX XX XXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX
XXXXXXX
BBBBBBBBBBBB
