BBBBBBB BBBBBBBBBBB

BBBBB BBBB
XXXX XXXXX XXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
	XX XXXXXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBXX
			 gettext(u'Answers') 
		XXXX
		XXXXX XXXXXXXXXXXXXXFFFFFFFFFXXXXXXX
	XXXX
	XX XXXXXXXXXXXXXXXXXXX
		BBB B BB BBBBBBBBBBBBBBBBB
			XX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBB BBBBXXXXXX
		BBBBBB
	XXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
				XXXXXXXXX
			XXXXXX
			BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
					XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX
						
					XXXXXXXXXXXXXXXXX
				XXXXXX
			BBBBB
		XXXXXX
	XXXXXX
	BBB B BB BBBBBBB
		BBBBBBB BBBBBBBBBBB BBBB BBBBBB
	BBBBB
		XXX gettext(u'There are no questions yet...') XXXX
	BBBBBB
	BBBBBBB BBBBBBBBBBBBBBBB
BBBBBBBB
