XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
		XXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
				XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
					XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
							XXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
				XXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
				  		BB BBBBBBBBBBBB B B XXXXXXXXXXX
				  		BBBB BBBBBBBBBBBB B B XXXXXXXXX
				  		BBBBB XXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
							XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
						XXXXXXX
						XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
							BB BBBBBBBBBBBB B B XXXXXXX
							BBBB BBBBBBBBBBBB B B XXXXXXX
						BBBBBXX
							
						XXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
							XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		BBBBB BBBB
		BBBBBBBB
	XXXXXX
XXXXXX
