XXXX XXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
	  XXX XXXXXXXXXXXXXXXXXXX
		BB BBBBBBBBBBBBBBBBBBBB
			XXXX
			  XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXX
			XXXXX
		BBBBB
		BB BBBBBBBBBBBBBBB B B
			XXXX
			  XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXX
			XXXXX
		BBBBB
		BBB B BB BBBBBBBBBB
				XXXXXX XXXXXXXXXXXXX
					BB B BB BBBBBBBB
						XXXXXXXXXXXXXXXX
					BBBBBXXXXXXXXXX
		BBBBBB
		BB BBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBB
			XXXX
			  XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXX
			XXXXX
		BBBBB
		BB BBBBBBBBBBBBBBBB
			XXXX
			  XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXX
			XXXXX
		BBBBB
	  XXXXX
	XXXXXX
XXXXXX