BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
	XXXXXXXXX
	BBBBBBB BBBBBBBBBBB BBBB BBBBBBBBBBBBB
	XXXX gettext(u'Answers:') XXXXX
	BBB B BB BBBBBBB
		BBBBBBB BBBBBBBBBBB BBBB BBBBBB
	BBBBB
		XXXX gettext(u'There are no answers yet...') XXXXX
		XXX gettext(u'You can be first!') XXXX
	BBBBBB
	XXXX
	XXXX gettext(u'Write your answer:') XXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBXX
		BBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Text') XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
			XXXXXX 
			XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter text of your answer') XXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				XXXXXXX
					XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'prove that your not a robot') X XXXXXXXXX
					 gettext(u'before you enter') 
				XXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Answer') XXXXXXXXX
		XXXXXX
	XXXXXXX
BBBBBBBB
