BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
	BBBBBBBBBB
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Nick') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your nick here') X XXXXXXXXX
		XXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter nick') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Enter password') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Mininum 6 charachters') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXXXXX
				XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'prove that your not a robot') X XXXXXXXXX
				 gettext(u'before you enter') 
			XXXXXXXX
		XXXXXX
	XXXXXX
	XXX
		XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Not registered yet?') XXXX
	XXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter') XXXXXXXXX
	XXXXXX
XXXXXXX
BBBBBBBB
