BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
	BBBBBBBBBB
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Login') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your login here') X XXXXXXXXX
		XXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your login') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Your e-mail') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Email') X XXXXXXXXXXXX gettext(u'Wrong e-mail') X XXXXXXXXX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your e-mail') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Nick') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your nick here') X XXXXXXXXX
		XXXXXX 
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your nick') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Enter password') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX XXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
				XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Mininum 6 charachters') XXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXX gettext(u'Error! Passwords is not match!') X XXXXXXXXXXXXX gettext(u'Repeat your password') X XXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Your avatar') XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Wrong e-mail') X XXXXXXXXX
		XXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Load your avatar') XXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXXXXX
				XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'prove that your not a robot') X XXXXXXXXX
				 gettext(u'before you enter') 
			XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Submit') XXXXXXXXX
	XXXXXX
XXXXXXX
BBBBBBBB
